### ISSUE TITLE
HOI-CL-OneStage/output//hoi_to_obj.pkl is missing 

### ISSUE THREAD

**Issue by suki1504** [zhihou7/HOI-CL-OneStage#2]
can you guid me to download the pkl file hoi_to_obj.pkl ,this is referenced in  the below code 
File "/home/harry/Videos/HOI-CL-OneStage/lib/modeling/roi_heads.py", line 50, in get_convert_matrix
    hoi_to_obj = pickle.load(open(DATA_DIR + '/hoi_to_obj.pkl', 'rb')) 
please find the below code trace
Traceback (most recent call last):
  File "train_net_atl.py", line 258, in <module>
    launch(
  File "/home/harry/.local/lib/python3.8/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net_atl.py", line 245, in main
    trainer = Trainer(cfg)
  File "train_net_atl.py", line 50, in __init__
    super().__init__(cfg)
  File "/home/harry/.local/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 376, in __init__
    model = self.build_model(cfg)
  File "/home/harry/.local/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 514, in build_model
    model = build_model(cfg)
  File "/home/harry/.local/lib/python3.8/site-packages/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/harry/Videos/HOI-CL-OneStage/lib/arch.py", line 36, in __init__
    self.roi_heads = build_roi_heads(cfg, self.backbone.output_shape())
  File "/home/harry/.local/lib/python3.8/site-packages/detectron2/modeling/roi_heads/roi_heads.py", line 43, in build_roi_heads
    return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
  File "/home/harry/Videos/HOI-CL-OneStage/lib/modeling/roi_heads.py", line 94, in __init__
    self._init_hoi_head(cfg, input_shape)
  File "/home/harry/Videos/HOI-CL-OneStage/lib/modeling/roi_heads.py", line 157, in _init_hoi_head
    self.hoi_predictor = HoiOutputLayers(cfg, self.hoi_head.output_shape)
  File "/home/harry/.local/lib/python3.8/site-packages/detectron2/config/config.py", line 189, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/home/harry/.local/lib/python3.8/site-packages/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/harry/Videos/HOI-CL-OneStage/lib/modeling/fast_rcnn.py", line 830, in from_config
    verb_to_HO_matrix, obj_to_HO_matrix = get_convert_matrix(obj_class_num=81)
  File "/home/harry/Videos/HOI-CL-OneStage/lib/modeling/roi_heads.py", line 50, in get_convert_matrix
    hoi_to_obj = pickle.load(open(DATA_DIR + '/hoi_to_obj.pkl', 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/harry/Videos/HOI-CL-OneStage/output//hoi_to_obj.pkl

**Comment by zhihou7** [comment]
Hi, you can find the file [here](https://github.com/zhihou7/HOI-CL/blob/master/misc/hoi_to_obj.pkl)

Feel free if you have further questions.
